services:
  server:
    container_name: python-scraper
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: ["flask", "run", "--debug", "--host", "0.0.0.0", "--port", "8000"]
  browser:
    image: selenium/standalone-firefox:latest
    shm_size: "2gb"
    ports:
      - "4444:4444"
      - "7900:7900"
